server:
  port: 8023

spring:
  application:
    name: product-service
  cloud:
    nacos:
      server-addr: 192.168.159.128:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false