server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.159.130:8858
      web-context-unify: false #默认调用链路收敛
    gateway:
      #路由规则
      routes:
        - id: order_route #路由的唯一表示
        #- id: stock_route
          uri: lb://order-seata #需要转发的地址  lb:使用nacos中的本地负载均衡策略,改成服务名order-service
          #断言规则 用于路由规则的匹配
          predicates:
            - Path=/order/**
            #http://localhost:8088/order-serv/order/add 路由到↓ 页面访问地址
            #http://localhost:8020/order-serv/order/add
            #- After=2022-02-26T13:00:00+08:00[Asia/Shanghai]
            #- Header=X-Request-Id,\d+   #请求头
            #- Method=GET
            #- Query=name  #localhost:8088/order/add?name
            #- Query=name,a  #localhost:8088/order/add?name=a
            #- CheckAuth=zhangsan2    #自定义断言工厂。CheckAuth是CheckAuthRoutePredicateFactory的前缀

          #filters:
            #- AddRequestHeader=X-Request-color, red #添加请求头
            #- StripPrefix=1  #转发之前去掉第一层路径，order-serv
            #- PrefixPath=/mall-order  #添加前缀 对应微服务需要配置context-path  server:servlet:ontext-path: /mall-order
             #http://localhost:8020/order/add
    #配置nacos
    nacos:
      discovery:
        server-addr: 192.168.159.130:8848
        username: nacos
        password: nacos




