server:
  port: 8040

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.159.128:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
#springboot默认日志是info，feign的debug级别不会输入
logging:
  level:
    com.tulin.order.openfeign: debug


#feign局部配置
feign:
  client:
    config:
      product-service:
        loggerLevel: BASIC
        #连接超时间默认2S
        connectTimeout: 5000
        #请求处理时间默认5S
        readTimeout: 3000

